### ISSUE TITLE
.masthead line image is not working

### ISSUE THREAD

**Issue by natalie-macpherson** [natalie-macpherson/dsn1676-assignment-1#1]
https://github.com/natalie-macpherson/dsn1676-assignment-1/blob/gh-pages/css/main.css#L28

The lines in the masthead don't seem to work. As far as I am able to see it should work. Could it be that I did not create the file properly.
-bring image into photoshop (reduce the size of the image to say the 4px) save as psd. and place it into the prod folder.
-resave the image as a png and place it into the image folder.
-link image to background in css under the .masthead class.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Did you figure this out?

**Comment by natalie-macpherson** [comment]
Yep, I used images/masthead-bg when my file that the image was located in was named was <em>image</em>. So once I got rid of the unneeded <em> s </em>  it worked.
